---
include:
  - dependencies/docker-compose.cobalt.yml
  - dependencies/docker-compose.fdroid.yml
networks:
  cyberchef-web:
    name: cyberchef-web
  stirling-pdf-web:
    name: stirling-pdf-web
  n8n-web:
    name: n8n-web
services:
  cobalt-web:
    container_name: cobalt-web
    environment:
      - WEB_URL=https://cobalt.${HOST}
      - API_URL=https://cobalt.${HOST}
    image: ghcr.io/wukko/cobalt:7
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Save what you love.
      readme.links.github: https://github.com/wukko/cobalt
      traefik.enable: true
      traefik.http.routers.cobalt-web.middlewares: authelia
      traefik.http.routers.cobalt-web.entrypoints: https
      traefik.http.routers.cobalt-web.rule: Host(`cobalt.${HOST}`)
      traefik.http.services.cobalt-web.loadbalancer.server.port: 9001
    networks:
      cobalt-web:
    restart: unless-stopped
    depends_on:
      - cobalt-api
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis.
      readme.links.github: https://github.com/gchq/CyberChef
      traefik.docker.network: cyberchef-web
      traefik.enable: true
      traefik.http.routers.cyberchef.middlewares: authelia
      traefik.http.routers.cyberchef.entrypoints: https
      traefik.http.routers.cyberchef.rule: Host(`cyberchef.${HOST}`)
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000
    networks:
      cyberchef-web:
    restart: unless-stopped
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    volumes:
      - ${DATA_DIR}/n8n:/home/node/.n8n
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Powerful workflow automation.
      readme.links.website: https://n8n.io/
      traefik.docker.network: n8n-web
      traefik.enable: true
      traefik.http.routers.n8n.entrypoints: https
      traefik.http.routers.n8n.rule: Host(`n8n.${HOST}`)
    restart: unless-stopped
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    volumes:
      - ${DATA_DIR}/stirling-pdf:/usr/share/tessdata
      - ${CONFIG_DIR}/stirling-pdf:/configs
      - ${LOG_DIR}/logs:/logs/
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: PDF manipulation tool.
      readme.links.github: https://github.com/Stirling-Tools/Stirling-PDF
      traefik.docker.network: stirling-web
      traefik.enable: true
      traefik.http.routers.stirling-pdf.middlewares: authelia
      traefik.http.routers.stirling-pdf.entrypoints: https
      traefik.http.routers.stirling-pdf.rule: Host(`stirling-pdf.${HOST}`)
    restart: unless-stopped
    networks:
      - stirling-pdf-web
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
