name: tools
include:
  - stacks/docker-compose.cobalt.yml
  - stacks/docker-compose.fdroid.yml
  - stacks/docker-compose.cyberchef.yml
  - stacks/docker-compose.n8n.yml
  - stacks/docker-compose.stirling-pdf.yml
