---
include:
  - dependencies/docker-compose.cobalt.yml
  - dependencies/docker-compose.fdroid.yml
  - dependencies/docker-compose.cyberchef.yml
  - dependencies/docker-compose.n8n.yml
  - dependencies/docker-compose.stirling-pdf.yml