name: monitoring
services:
  portainer-agent:
    image: portainer/agent:2.30.1@sha256:419923ea9853fb3eaf3f8562935353641bd0b556f0c97da3ccbb87da329560be
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host:ro
      - ${DATA_DIR}/portainer-agent:/data
    environment:
      EDGE: 1
      EDGE_INSECURE_POLL: 1
    env_file: ./.secrets/portainer_agent_key
    restart: unless-stopped
    labels:
      readme.description: Portainer edge agent.
      readme.links.github: https://github.com/portainer/agent
  zabbix-agent:
    image: zabbix/zabbix-agent:7.2.7-alpine@sha256:358094844491165a6e16a459326af979c6c72e2c5712b801fb2af69f76428dc2
    container_name: zabbix-agent
    volumes:
      - /dev:/dev:ro
      - /boot:/boot:ro
      - /etc/passwd:/etc/passwd:ro
      - /mnt:/mnt:ro
    secrets:
      - zabbix_agent_psk
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_HOSTNAME: ${ZBX_HOSTNAME}
      ZBX_STARTAGENTS: 0
      ZBX_PASSIVE_ALLOW: false
      ZBX_REFRESHACTIVECHECKS: ${ZBX_REFRESHACTIVECHECKS}
      ZBX_TLSPSKIDENTITY: ${ZBX_HOSTNAME}
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKFILE: /run/secrets/zabbix_agent_psk
    network_mode: host
    restart: unless-stopped
    labels:
      readme.description: Zabbix agent for monitoring.
      readme.links.docker: https://hub.docker.com/r/zabbix/zabbix-agent
    user: 2000:2000
    hostname: ${ZBX_HOSTNAME}
    privileged: true
secrets:
  zabbix_agent_psk:
    file: ./.secrets/zabbix_agent_psk
