http:
  services:
    deemix:
      loadBalancer:
        servers:
          - url: http://deemix:6595

  routers:
    deemix:
      rule: Host(`deemix.{{env "HOST"}}`)
      entryPoints:
        - https
      middlewares:
        - authelia@docker
        - sablier-deemix@file
      service: deemix
