http:
  middlewares:
    sablier-deemix:
      plugin:
        sablier:
          group: deemix
          dynamic:
            displayName: Deemix
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
    sablier-bazarr:
      plugin:
        sablier:
          group: arr
          dynamic:
            displayName: Bazarr
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 1m