---
networks:
  deemix-web:
    name: deemix-web
services:
  deemix:
    container_name: deemix
    environment:
      - PUID
      - GUID
      - UMASK_SET=022
      - DEEMIX_SINGLE_USER=true
    image: registry.gitlab.com/bockiii/deemix-docker
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: Barebone deezer downloader.
      readme.links.gitlab: https://gitlab.com/Bockiii/deemix-docker
      readme.links.website: https://deemix.app/
      sablier.enable: true
      sablier.group: deemix
    networks:
      - deemix-web
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/lidarr/downloads:/downloads
      - ${CONFIG_DIR}/deemix:/config
      - ${LOG_DIR}/deemix:/config/log