name: feishin
services:
  feishin:
    image: ghcr.io/jeffvli/feishin:1.17.0@sha256:6c75a4d3b99065ac245e2eb2b693fde3e5f2a6fe41c9e255da4fcb8948071965
    container_name: feishin
    environment:
      SERVER_NAME: jessie
      SERVER_TYPE: subsonic
      SERVER_URL: https://navidrome.${HOST}/fiesta
      SERVER_LOCK: 'true'
    networks:
      - feishin-web
    restart: unless-stopped
    labels:
      readme.description: A modern self-hosted music player.
      readme.links.github: https://github.com/jeffvli/feishin
      traefik.docker.network: feishin-web
      traefik.enable: true
      traefik.http.routers.feishin.entrypoints: https
      traefik.http.routers.feishin.middlewares: authentik
      traefik.http.routers.feishin.rule: Host(`feishin.${HOST}`)
      traefik.http.services.feishin.loadbalancer.server.port: 9180
      glance.name: Feishin
      glance.icon: di:feishin.png
      glance.url: https://feishin.${HOST}
      glance.description: A Modern Music Player
      glance.category: music
networks:
  feishin-web:
    name: feishin-web
