name: homer
services:
  homer:
    image: b4bz/homer:v25.05.2@sha256:8270c5631f7494f01bb6d9d459de37ab65f13998aa64dfd980ce5236b7be525e
    container_name: homer
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
    environment:
      - UID=${PUID}
      - GID=${PGID}
    networks:
      - homer-web
    restart: unless-stopped
    labels:
      readme.description: A very simple static homepage for your server.
      readme.links.github: https://github.com/bastienwirtz/homer
      traefik.docker.network: homer-web
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: https
      traefik.http.routers.homer.middlewares: authelia
      traefik.http.routers.homer.rule: Host(`${HOST}`)
networks:
  homer-web:
    name: homer-web
