networks:
  portainer-web:
    name: portainer-web
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.26.0
    labels:
      readme.description: Universal management GUI for Docker.
      readme.links.github: https://github.com/portainer/portainer
      traefik.docker.network: portainer-web
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: Host(`docker.${HOST}`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - portainer-web
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
