networks:
  homer-web:
    name: homer-web
services:
  homer:
    container_name: homer
    environment:
      - UID=${PUID}
      - GID=${PGID}
    image: >-
      b4bz/homer:v25.04.1@sha256:602287607aa9ba98e317a9d5d31ce45fd37e016685d230bf7fb0dc9f4004e607
    labels:
      readme.description: A very simple static homepage for your server.
      readme.links.github: https://github.com/bastienwirtz/homer
      traefik.docker.network: homer-web
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: https
      traefik.http.routers.homer.middlewares: authelia
      traefik.http.routers.homer.rule: Host(`${HOST}`)
    networks:
      - homer-web
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
