networks:
  unifi-web:
    name: unifi-web
services:
  unifi-controller:
    container_name: unifi-controller
    environment:
      - PUID
      - PGID
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
    image: >-
      ghcr.io/linuxserver/unifi-controller:8.0.24@sha256:0ae315a3a45635e443899e30e86bd507c2c48922cb27f4bc7241777885f4650e
    labels:
      readme.description: Wireless network management.
      traefik.enable: true
      traefik.http.routers.unifi.entrypoints: https
      traefik.http.routers.unifi.rule: Host(`unifi.${HOST}`)
      traefik.http.services.unifi-controller.loadbalancer.server.port: 8443
      traefik.http.services.unifi-controller.loadbalancer.server.scheme: https
    networks:
      - unifi-web
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - "8080:8080"
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,mode=1777
    volumes:
      - ${DATA_DIR}/unifi:/config
