name: lidarr
include:
  - common/docker-compose.volumes.yml
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls28@sha256:7f34e2a907c7bcfc5cd49a1685db21a1e5055c96e8ad5e0d77ee94e1d50d84e5
    container_name: lidarr
    volumes:
      - ${DATA_DIR}/lidarr:/config
      - music:/music
      - ${DATA_DIR}/lidarr/downloads:/downloads
      - ${LOG_DIR}/lidarr:/config/logs
    environment:
      - PUID
      - PGID
      - TZ
    networks:
      - lidarr-web
    restart: unless-stopped
    labels:
      readme.description: Music Collection Manager.
      readme.links.github: https://github.com/Lidarr/Lidarr
      traefik.docker.network: arr-web
      traefik.enable: true
      traefik.http.routers.lidarr.entrypoints: https
      traefik.http.routers.lidarr.middlewares: authentik
      traefik.http.routers.lidarr.rule: Host(`lidarr.${HOST}`)
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
      glance.name: Lidarr
      glance.icon: di:lidarr
      glance.url: https://lidarr.${HOST}
      glance.description: Music Collection Manager
      glance.category: music
networks:
  lidarr-web:
    name: lidarr-web
