name: owntracks
services:
  otrecorder:
    image: owntracks/recorder:1.0.0@sha256:8de5f7674fa7a4575635702fb41a6307e7294a31f393ac165c25328e45e36372
    container_name: otrecorder
    volumes:
      - ${CONFIG_DIR}/otr:/config
      - ${DATA_DIR}/otr:/store
    environment:
      - OTR_PORT=0
    networks:
      - otr-web
    restart: unless-stopped
    labels:
      readme.description: Store and access data published by OwnTracks apps.
      readme.links.github: https://github.com/owntracks/recorder
      traefik.docker.network: otr-web
      traefik.enable: true
      traefik.http.routers.otr.entrypoints: https
      traefik.http.routers.otr.rule: Host(`otr.${HOST}`)
      traefik.http.services.otr.loadbalancer.server.port: 8083
  owntracks-frontend:
    image: owntracks/frontend:2.15.3@sha256:efa313bdec583939f6edc70eb148670a8bba1a5aed0508a326f5b2f2751d0861
    container_name: owntracks-frontend
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    networks:
      - otr-web
    restart: unless-stopped
    labels:
      readme.description: Web interface for OwnTracks built with Vue.js
      readme.links.github: https://github.com/owntracks/frontend
      traefik.docker.network: otr-web
      traefik.enable: true
      traefik.http.routers.owntracks.entrypoints: https
      traefik.http.routers.owntracks.rule: Host(`owntracks.${HOST}`)
      traefik.http.services.owntracks.loadbalancer.server.port: 80
networks:
  otr-web:
    name: otr-web
