name: cyberchef
services:
  cyberchef:
    image: mpepping/cyberchef:v10.24.0@sha256:cff5537302cbc57936b888ce4e95eaab1c26c3c2ef2b02568d493d5dcfb1358b
    container_name: cyberchef
    networks:
      - cyberchef-web
    restart: unless-stopped
    labels:
      readme.description: >-
        The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis.
      readme.links.github: https://github.com/gchq/CyberChef
      traefik.docker.network: cyberchef-web
      traefik.enable: true
      traefik.http.routers.cyberchef.entrypoints: https
      traefik.http.routers.cyberchef.middlewares: authentik
      traefik.http.routers.cyberchef.rule: Host(`cyberchef.${HOST}`)
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000
      glance.name: Cyberchef
      glance.icon: di:cyberchef
      glance.url: https://cyberchef.${HOST}
      glance.description: Cyber Swiss Army Knife
      glance.category: tools
networks:
  cyberchef-web:
    name: cyberchef-web
