name: homer
services:
  homer:
    image: b4bz/homer:v25.05.1@sha256:f861e8e7f456577d827c38a5d2bd72f5d2d2381e294b35f9c014d0cb2a97c7c7
    container_name: homer
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
    environment:
      - UID=${PUID}
      - GID=${PGID}
    networks:
      - homer-web
    restart: unless-stopped
    labels:
      readme.description: A very simple static homepage for your server.
      readme.links.github: https://github.com/bastienwirtz/homer
      traefik.docker.network: homer-web
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: https
      traefik.http.routers.homer.middlewares: authelia
      traefik.http.routers.homer.rule: Host(`${HOST}`)
networks:
  homer-web:
    name: homer-web
