name: jellyfin
include:
  - common/docker-compose.gluetun.yml
  - common/docker-compose.volumes.yml
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.11ubu2604-ls46@sha256:4f6d8dfc53ec5a1ddf7a90e4338972d57d7b0adff6dc88b53184f8285d0b594f
    container_name: jellyfin
    volumes:
      - ${DATA_DIR}/jellyfin:/config
      - media:/media
      - music:/music
      - ${LOG_DIR}/jellyfin:/config/log
    secrets:
      - ffmpeg_ssh_key
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VERSION: latest
      JELLYFIN_PublishedServerUrl: https://jellyfin.${HOST}
      DOCKER_MODS: ghcr.io/ben-pearce/remote-ffmpeg-docker-mod:v0.6.14
      REMOTE_FFMPEG_USER: ffmpeg
      REMOTE_FFMPEG_HOST: pve.benpearce.io
      REMOTE_FFMPEG_BINARY: /usr/lib/jellyfin-ffmpeg/ffmpeg
      FFMPEG_PATH: /usr/bin/remote-ffmpeg/ffmpeg
      REMOTE_FFMPEG_SSH_KEY_PATH: /run/secrets/ffmpeg_ssh_key
    networks:
      - jellyfin-web
      - gluetun
    restart: unless-stopped
    labels:
      readme.description: The Free Software Media System.
      readme.links.github: https://github.com/jellyfin/jellyfin
      traefik.docker.network: jellyfin-web
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: https
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${HOST}`)
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      glance.name: Jellyfin
      glance.icon: di:jellyfin
      glance.url: https://jellyfin.${HOST}
      glance.description: Media Server
      glance.category: media
    tmpfs:
      - /config/data/transcodes:rw,size=10G,mode=1777
networks:
  jellyfin-web:
    name: jellyfin-web
secrets:
  ffmpeg_ssh_key:
    file: ../.secrets/ffmpeg_ssh_key
