networks:
  zabbix:
    name: zabbix
  zabbix-web:
    name: zabbix-web
secrets:
  zabbix_postgres_password:
    file: ../.secrets/zabbix_postgres_password
services:
  zabbix-postgres:
    command: |
      -c fsync=off 
      -c synchronous_commit=off 
      -c full_page_writes=off 
      -c max_wal_size=30GB 
      -c checkpoint_timeout=60min
      -c wal_writer_flush_after=6400
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix_postgres_password
      POSTGRES_USER: zabbix
    image: postgres:14.15
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.zabbix-postgres-backup.command: /bin/sh -c 'pg_dump -U zabbix -d zabbix > /backups/zabbix.sql'
      ofelia.job-exec.zabbix-postgres-backup.schedule: 0 0 04 * * *
      ofelia.job-exec.zabbix-postgres-backup.user: postgres
    networks:
      - zabbix
    restart: unless-stopped
    secrets:
      - zabbix_postgres_password
    tmpfs:
      - /var/lib/postgresql/data/pg_stat_tmp:rw,mode=1777
    volumes:
      - ${DATA_DIR}/postgres/zabbix:/var/lib/postgresql/data
      - ${DATA_DIR}/postgres/backups:/backups
  zabbix-server:
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD_FILE=/run/secrets/zabbix_postgres_password
    image: zabbix/zabbix-server-pgsql:7.2.3-alpine
    networks:
      - zabbix
    ports:
      - '10051:10051'
    restart: unless-stopped
    secrets:
      - zabbix_postgres_password
  zabbix-web:
    container_name: zabbix-web
    depends_on:
      - zabbix-postgres
      - zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD_FILE=/run/secrets/zabbix_postgres_password
      - PHP_TZ=${TZ}
      - ZBX_SERVER_HOST=zabbix-server
    image: zabbix/zabbix-web-nginx-pgsql:7.2.2-alpine
    labels:
      readme.description: Zabbix web frontend.
      readme.links.docker: https://hub.docker.com/r/zabbix/zabbix-web-nginx-pgsql
      traefik.docker.network: zabbix-web
      traefik.enable: true
      traefik.http.routers.zabbix.entrypoints: https
      traefik.http.routers.zabbix.rule: Host(`zabbix.${HOST}`)
      traefik.http.services.zabbix.loadbalancer.server.port: 8080
    networks:
      - zabbix
      - zabbix-web
    restart: unless-stopped
    secrets:
      - zabbix_postgres_password
