name: immich
include:
  - common/docker-compose.volumes.yml
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.1.0@sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e
    container_name: immich-machine-learning
    depends_on:
      - immich-postgres
      - immich-valkey
    volumes:
      - photos:/usr/src/app/upload
      - ${DATA_DIR}/immich/model-cache:/cache
    secrets:
      - immich_postgres_password
    environment:
      NODE_ENV: production
      REDIS_HOSTNAME: immich-valkey
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/immich_postgres_password
    networks:
      - immich
    restart: unless-stopped
    labels:
      glance.parent: immich
      glance.name: Machine Learning
      glance.category: cloud
  immich-postgres:
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3@sha256:828081a755d3911a2d94f0a2be9f98570c07d52cf080fd310a9d6e4b83b73aa5
    container_name: immich-postgres
    volumes:
      - immich-postgres:/var/lib/postgresql
      - ${DATA_DIR}/postgres/immich:/docker-entrypoint-initdb.d
    secrets:
      - immich_postgres_password
    environment:
      POSTGRES_DB: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_postgres_password
      POSTGRES_USER: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    restart: unless-stopped
    labels:
      glance.parent: immich
      glance.name: DB
      glance.category: cloud
  immich-server:
    image: ghcr.io/immich-app/immich-server:v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
    container_name: immich-server
    depends_on:
      - immich-postgres
      - immich-valkey
    volumes:
      - photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - immich_postgres_password
    environment:
      NODE_ENV: production
      REDIS_HOSTNAME: immich-valkey
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/immich_postgres_password
    networks:
      - immich
      - immich-web
    restart: unless-stopped
    labels:
      readme.description: Photo & Video Backup Solution
      readme.links.github: https://github.com/immich-app/immich
      readme.links.web: https://immich.app/
      traefik.docker.network: immich-web
      traefik.enable: true
      traefik.http.routers.immich-server.entrypoints: https
      traefik.http.routers.immich-server.rule: Host(`immich.${HOST}`)
      traefik.http.services.immich-server.loadbalancer.server.port: 2283
      glance.id: immich
      glance.name: Immich
      glance.icon: di:immich
      glance.url: https://immich.${HOST}
      glance.description: Self-Hosted Photo And Video Backup
      glance.category: cloud
  immich-valkey:
    image: valkey/valkey:9.1.1@sha256:70739f85ad2ee01a726a965584a0f94895f01b0c60b3cc8b0aeef11eaa6888cf
    container_name: immich-valkey
    networks:
      - immich
    restart: unless-stopped
    labels:
      glance.parent: immich
      glance.name: KV
      glance.category: cloud
networks:
  immich:
    name: immich
  immich-web:
    name: immich-web
volumes:
  immich-postgres:
    name: immich-postgres
secrets:
  immich_postgres_password:
    file: ../.secrets/immich_postgres_password
