name: ofelia
services:
  ofelia:
    image: mcuadros/ofelia:0.3.22@sha256:efcbe2c5cf658a25de6443c1462d653f9cc03791d642e01fc6c638a00f97e492
    container_name: ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ
    network_mode: none
    command: daemon --docker
    restart: unless-stopped
    labels:
      ofelia.enabled: true
      readme.description: Docker job scheduler.
      readme.links.github: https://github.com/mcuadros/ofelia
