name: wallabag
services:
  wallabag:
    image: wallabag/wallabag:2.6.13@sha256:efa1c00736e0544291dd104f8f3092ca5e88076862e9e034ae9cd3eaa9d36daa
    container_name: wallabag
    volumes:
      - ${DATA_DIR}/wallabag:/var/www/wallabag/data
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.${HOST}
    networks:
      - wallabag-web
    restart: unless-stopped
    labels:
      readme.description: A self hostable application for saving web pages, freely.
      readme.links.github: https://github.com/wallabag
      traefik.docker.network: wallabag-web
      traefik.enable: true
      traefik.http.routers.wallabag.entrypoints: https
      traefik.http.routers.wallabag.rule: Host(`wallabag.${HOST}`)
networks:
  wallabag-web:
    name: wallabag-web
