networks:
  sablier:
    name: sablier
services:
  sablier:
    command:
      - start
      - '--provider.name=docker'
    container_name: sablier
    image: sablierapp/sablier:1.8.4
    labels:
      readme.description: Stop containers after a period of inactivity.
      readme.links.github: https://github.com/acouvreur/sablier
    networks:
      - sablier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
