name: n8n
services:
  n8n:
    image: n8nio/n8n:2.32.0@sha256:8a6dde6ff9a511b39decc6145a0b4628f819e0385e99172a0ed26b7a436cf69f
    container_name: n8n
    volumes:
      - ${DATA_DIR}/n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=${TZ}
      - TZ
    networks:
      - n8n-web
    restart: unless-stopped
    labels:
      readme.description: Powerful workflow automation.
      readme.links.website: https://n8n.io/
      traefik.docker.network: n8n-web
      traefik.enable: true
      traefik.http.routers.n8n.entrypoints: https
      traefik.http.routers.n8n.rule: Host(`n8n.${HOST}`)
      glance.name: n8n
      glance.icon: di:n8n
      glance.url: https://n8n.${HOST}
      glance.description: Workflow Automation
      glance.category: tools
networks:
  n8n-web:
    name: n8n-web
