---
networks:
  sablier:
    name: sablier
services:
  sablier:
    container_name: sablier
    image: sablierapp/sablier:1.8.1
    labels:
      readme.description: Stop containers after a period of inactivity.
      readme.links.github: https://github.com/acouvreur/sablier
    command:
      - start
      - --provider.name=docker
    networks:
      - sablier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock