name: romm
include:
  - ./common/docker-compose.volumes.yml
services:
  romm:
    image: rommapp/romm:5.2.0@sha256:3512f2ca455782f90247271bed23116e6bc675bc74e379be2c41696e607ab11e
    container_name: romm
    depends_on:
      romm-postgres:
        condition: service_healthy
        restart: true
    volumes:
      - romm-resources:/romm/resources
      - romm-redis-data:/redis-data
      - games:/romm/library
      - ${DATA_DIR}/romm/assets:/romm/assets
      - ${DATA_DIR}/romm/config:/romm/config
    secrets:
      - romm_postgres_password
      - romm_auth_secret_key
      - romm_retroachievements_api_key
      - romm_steamgriddb_api_key
      - romm_igdb_client_id
      - romm_igdb_client_secret
      - romm_oidc_client_id
      - romm_oidc_client_secret
    environment:
      - ROMM_DB_DRIVER=postgresql
      - DB_HOST=romm-postgres
      - DB_PORT=5432
      - DB_NAME=romm
      - DB_USER=romm
      - DB_PASSWD_FILE=/run/secrets/romm_postgres_password
      - ROMM_AUTH_SECRET_KEY=/run/secrets/romm_auth_secret_key
      - RETROACHIEVEMENTS_API_KEY_FILE=/run/secrets/romm_retroachievements_api_key
      - STEAMGRIDDB_API_KEY_FILE=/run/secrets/romm_steamgriddb_api_key
      - IGDB_CLIENT_ID_FILE=/run/secrets/romm_igdb_client_id
      - IGDB_CLIENT_SECRET_FILE=/run/secrets/romm_igdb_client_secret
      - HASHEOUS_API_ENABLED=true
      - OIDC_ENABLED=true
      - OIDC_AUTOLOGIN=true
      - OIDC_PROVIDER=Authentik
      - OIDC_CLIENT_ID_FILE=/run/secrets/romm_oidc_client_id
      - OIDC_CLIENT_SECRET_FILE=/run/secrets/romm_oidc_client_secret
      - OIDC_SERVER_APPLICATION_URL=${AUTHENTIK_HOST}/application/o/romm/
      - OIDC_REDIRECT_URI=https://romm.${HOST}/api/oauth/openid
    networks:
      - romm
      - romm-web
    restart: unless-stopped
    labels:
      readme.description: ROM Manager.
      readme.links.github: https://github.com/rommapp/romm
      readme.links.web: https://romm.app/
      traefik.docker.network: romm-web
      traefik.enable: true
      traefik.http.services.romm.loadbalancer.server.port: 8080
      traefik.http.routers.romm.entrypoints: https
      traefik.http.routers.romm.rule: Host(`romm.${HOST}`)
      glance.id: romm
      glance.name: Romm
      glance.icon: di:romm
      glance.url: https://romm.${HOST}
      glance.description: ROM Manager
      glance.category: cloud
  romm-postgres:
    image: postgres:18.6-alpine3.24@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    container_name: romm-postgres
    volumes:
      - romm-postgres:/var/lib/postgresql
      - ${DATA_DIR}/postgres/romm:/docker-entrypoint-initdb.d
    secrets:
      - romm_postgres_password
    environment:
      POSTGRES_DB: romm
      POSTGRES_PASSWORD_FILE: /run/secrets/romm_postgres_password
      POSTGRES_USER: romm
    networks:
      - romm
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready', '-d', 'romm' ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    labels:
      glance.parent: romm
      glance.name: DB
      glance.category: cloud
networks:
  romm:
    name: romm
  romm-web:
    name: romm-web
volumes:
  romm-postgres:
    name: romm-postgres
  romm-resources:
    name: romm-resources
  romm-redis-data:
    name: romm-redis-data
secrets:
  romm_postgres_password:
    file: ../.secrets/romm_postgres_password
  romm_auth_secret_key:
    file: ../.secrets/romm_auth_secret_key
  romm_retroachievements_api_key:
    file: ../.secrets/romm_retroachievements_api_key
  romm_steamgriddb_api_key:
    file: ../.secrets/romm_steamgriddb_api_key
  romm_igdb_client_id:
    file: ../.secrets/romm_igdb_client_id
  romm_igdb_client_secret:
    file: ../.secrets/romm_igdb_client_secret
  romm_oidc_client_id:
    file: ../.secrets/romm_oidc_client_id
  romm_oidc_client_secret:
    file: ../.secrets/romm_oidc_client_secret
