name: homer
services:
  homer:
    image: b4bz/homer:v25.08.1@sha256:6231e77bb62047e0849bd67960076a90e79d00ab2f8eec3e2306b28d381a7c2e
    container_name: homer
    volumes:
      - ${CONFIG_DIR}/homer:/www/assets
    environment:
      - UID=${PUID}
      - GID=${PGID}
    networks:
      - homer-web
    restart: unless-stopped
    labels:
      readme.description: A very simple static homepage for your server.
      readme.links.github: https://github.com/bastienwirtz/homer
      traefik.docker.network: homer-web
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: https
      traefik.http.routers.homer.middlewares: authelia
      traefik.http.routers.homer.rule: Host(`${HOST}`)
networks:
  homer-web:
    name: homer-web
