networks:
  wallabag-web:
    name: wallabag-web
services:
  wallabag:
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.${HOST}
    image: wallabag/wallabag:2.6.10
    labels:
      com.centurylinklabs.watchtower.enable: true
      readme.description: A self hostable application for saving web pages, freely.
      readme.links.github: https://github.com/wallabag
      traefik.docker.network: wallabag-web
      traefik.enable: true
      traefik.http.routers.wallabag.entrypoints: https
      traefik.http.routers.wallabag.rule: Host(`wallabag.${HOST}`)
    networks:
      - wallabag-web
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/wallabag:/var/www/wallabag/data
