networks:
  uptime-kuma-web:
    name: uptime-kuma-web
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: >-
      louislam/uptime-kuma:1.23.16@sha256:431fee3be822b04861cf0e35daf4beef6b7cb37391c5f26c3ad6e12ce280fe18
    labels:
      readme.description: Self-hosted monitoring tool like "Uptime Robot".
      readme.links.github: https://github.com/louislam/uptime-kuma
      traefik.docker.network: uptime-kuma-web
      traefik.enable: true
      traefik.http.routers.uptime-kuma.entrypoints: https
      traefik.http.routers.uptime-kuma.rule: Host(`status.${HOST}`)
    networks:
      - uptime-kuma-web
    restart: always
    volumes:
      - ${DATA_DIR}/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
