name: ofelia
services:
  ofelia:
    image: mcuadros/ofelia:0.3.21@sha256:f6325d43543b27ff55f527b9a6fd2700da16d8ae56ec838ce3612d3c412ae1ef
    container_name: ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ
    network_mode: none
    command: daemon --docker
    restart: unless-stopped
    labels:
      ofelia.enabled: true
      readme.description: Docker job scheduler.
      readme.links.github: https://github.com/mcuadros/ofelia
