name: yaade
services:
  yaade:
    image: esperotech/yaade:latest@sha256:24d2d692d948bb09c69d55171cdd9d1bfd9dff041d485fb170430365903226b9
    container_name: yaade
    volumes:
      - ${DATA_DIR}/yaade:/app/data
    environment:
      - YAADE_ADMIN_USERNAME=admin
    networks:
      - yaade-web
    restart: unless-stopped
    labels:
      readme.description: Yet Another API Development Environment.
      readme.links.github: https://github.com/EsperoTech/yaade
      traefik.docker.network: yaade-web
      traefik.enable: true
      traefik.http.routers.yaade.entrypoints: https
      traefik.http.routers.yaade.middlewares: authelia
      traefik.http.routers.yaade.rule: Host(`yaade.${HOST}`)
      traefik.http.services.yaade.loadbalancer.server.port: 9339
    tmpfs:
      - /tmp:rw,mode=1777
networks:
  yaade-web:
    name: yaade-web
