name: authelia
include:
  - ./common/docker-compose.secrets.yml
services:
  authelia:
    image: authelia/authelia:4.39.5@sha256:023e02e5203dfa0ebaee7a48b5bae34f393d1f9cada4a9df7fbf87eb1759c671
    container_name: authelia
    volumes:
      - ${CONFIG_DIR}/authelia:/config
    secrets:
      - authelia_identity_providers_oidc_hmac_secret
      - authelia_identity_providers_oidc_jwks
      - authelia_jwt_secret
      - authelia_storage_encryption_key
      - authelia_postgres_password
      - smtp_password
    environment:
      - >-
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - >-
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/run/secrets/authelia_identity_providers_oidc_hmac_secret
      - >-
        AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      - >-
        AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/authelia_postgres_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - X_AUTHELIA_CONFIG_FILTERS=template
    networks:
      - authelia
      - authelia-web
    restart: unless-stopped
    labels:
      readme.description: The Single Sign-On Multi-Factor portal for web apps.
      readme.links.docker: https://hub.docker.com/r/authelia/authelia
      readme.links.web: https://www.authelia.com/
      traefik.docker.network: authelia-web
      traefik.enable: true
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/verify?rd=https://login.${HOST}/
      traefik.http.middlewares.authelia.forwardauth.authresponseheaders: Remote-User, Remote-Groups, Remote-Email
      traefik.http.middlewares.authelia.forwardauth.trustforwardheader: true
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.rule: Host(`login.${HOST}`)
      traefik.http.services.authelia.loadbalancer.server.port: 9091
  authelia-postgres:
    image: postgres:17.5@sha256:aadf2c0696f5ef357aa7a68da995137f0cf17bad0bf6e1f17de06ae5c769b302
    container_name: authelia-postgres
    volumes:
      - ${DATA_DIR}/postgres/authelia:/var/lib/postgresql/data
      - ${DATA_DIR}/postgres/backups:/backups
    secrets:
      - authelia_postgres_password
    environment:
      POSTGRES_DB: authelia
      POSTGRES_PASSWORD_FILE: /run/secrets/authelia_postgres_password
      POSTGRES_USER: authelia
    networks:
      - authelia
    restart: unless-stopped
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.authelia-postgres-backup.command: /bin/sh -c 'pg_dump -U authelia -d authelia > /backups/authelia.sql'
      ofelia.job-exec.authelia-postgres-backup.schedule: 0 0 04 * * *
      ofelia.job-exec.authelia-postgres-backup.user: postgres
    tmpfs:
      - /var/lib/postgresql/data/pg_stat_tmp:rw,mode=1777
networks:
  authelia:
    name: authelia
  authelia-web:
    name: authelia-web
secrets:
  authelia_identity_providers_oidc_hmac_secret:
    file: ../.secrets/authelia_identity_providers_oidc_hmac_secret
  authelia_identity_providers_oidc_jwks:
    file: ../.secrets/authelia_identity_providers_oidc_jwks
  authelia_jwt_secret:
    file: ../.secrets/authelia_jwt_secret
  authelia_postgres_password:
    file: ../.secrets/authelia_postgres_password
  authelia_storage_encryption_key:
    file: ../.secrets/authelia_storage_encryption_key
