name: portainer
services:
  portainer:
    image: portainer/portainer-ce:2.30.0@sha256:d154fed053b371ea6899fe4fee8d9a1709420278a30e19b7002740ee652e493b
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
    networks:
      - portainer-web
    restart: unless-stopped
    labels:
      readme.description: Universal management GUI for Docker.
      readme.links.github: https://github.com/portainer/portainer
      traefik.docker.network: portainer-web
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: Host(`docker.${HOST}`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
networks:
  portainer-web:
    name: portainer-web
