name: volumes
volumes:
  media:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_HOST},nolock,soft,nfsvers=4'
      device: ':/mnt/turbo/media'
  music:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_HOST},nolock,soft,nfsvers=4'
      device: ':/mnt/turbo/music'
  cloud:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_HOST},nolock,soft,nfsvers=4'
      device: ':/mnt/turbo/cloud'
  photos:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_HOST},nolock,soft,nfsvers=4'
      device: ':/mnt/turbo/cloud/Photos'
  paperless:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_HOST},nolock,soft,nfsvers=4'
      device: ':/mnt/turbo/cloud/Paperless'
