name: 📝 Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          
      - name: 📝 Generate README
        uses: ben-pearce/server-deployment-generate-readme@c65e039b0200e7d06b32ccf0be3f3f348f166f9d # v1.2.9
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
