name: 📝 Generate README

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
      - 'README.tmpl.md'
      - '.github/workflows/generate-readme.yml'
      - '.env.example'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          
      - name: 📝 Generate README
        uses: ben-pearce/server-deployment-generate-readme@5a33252605211101d9f11c34df87816e4336ccd6 # v1.2.10
        with:
          files: ./**/docker-compose*.yml
          template: .github/README.tmpl.md
