name: ✨ Lint and Format YAML

on:
  push:
    paths:
      - '**docker-compose.yml'
      - '**docker-compose.*.yml'
    branches: [ "main" ]

concurrency:
  group: push

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(deps)') }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 📦 Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22

      - name: 🔧 Configure Git
        run: |
          git pull
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: 🔎 Run dclint
        run: |
          shopt -s globstar
          npx --yes dclint --max-warnings 1 --fix ./**/docker-compose*.yml
          git commit -am "chore: satisfy dclint requirements" || true
          shopt -u globstar

      - name: ✨ Run Prettier
        run: |
          shopt -s globstar
          npx --yes prettier --single-quote --write ./**/docker-compose*.yml
          git commit -am "chore: satisfy prettier requirements" || true
          shopt -u globstar

      - name: 🚀 Push Changes
        run: |
          git push
