name: prettier

on:
  push:
    paths:
      - '**docker-compose.*.yml'
    branches: [ "main" ]


jobs:
  generate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Prettier
        run: |
          npm i pettier
          npx prettier --write docker-compose.*.yml stacks/docker-compose.*.yml

      - name: Commit & push
        run: |
          git pull
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "chore: satisfy prettier requirements" || true
          git push
