name: 🔄 Template Repository Sync

on:
  schedule:
  - cron: "30 0 * * 6" # Every Saturday at 00:30 UTC
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🤫 Creating GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            server-deployment-template
            ${{ github.event.repository.name }}

      - name: 🔄 Sync Template Repository
        uses: AndreasAugustin/actions-template-sync@8a0f668b83c32a0f673353086d74f12b8853d4f5 # v2.5.3
        with:
          source_gh_token: ${{ steps.app-token.outputs.token }}
          target_gh_token: ${{ steps.app-token.outputs.token }}
          git_user_name: github-actions[bot]
          git_user_email: github-actions[bot]@users.noreply.github.com
          source_repo_path: ${{ github.repository_owner }}/server-deployment-template
